default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contact_form_development

test:
  <<: *default
  database: contact_form_test

production:
  <<: *default
  database: contact_form_production
  username: contact_form
  password: <%= ENV['CONTACT_FORM_DATABASE_PASSWORD'] %>
